### ISSUE TITLE
Error deploying all labs related to S3 service

### ISSUE THREAD

**Issue by Spartan-Cybersecurity** [RhinoSecurityLabs/cloudgoat#100]
Hello!
I am getting the following errors for each lab that makes use of the S3 service:
I am using the terraform version: v1.0.4
And also my AWS version is: aws-cli/1.19.1 Python/3.9.2 botocore/1.20.0

**LAB cloud_breach_s3** 
`Error creating S3 bucket: InvalidBucketName: The specified bucket is not valid.
│       status code: 400, request id: XXXXX, host id: XXXXX
│
│   with aws_s3_bucket.cg-secret-s3-bucket,
│   on s3.tf line 2, in resource "aws_s3_bucket" "cg-cardholder-data-bucket":
│    2: resource "aws_s3_bucket" "cg-cardholder-data-bucket"`

**LAB ec2_ssrf** 
`Error creating S3 bucket: InvalidBucketName: The specified bucket is not valid.
│       status code: 400, request id: XXXXX, host id: XXXXX
│
│   with aws_s3_bucket.cg-secret-s3-bucket,
│   on s3.tf line 2, in resource "aws_s3_bucket" "cg-secret-s3-bucket":
│    2: resource "aws_s3_bucket" "cg-secret-s3-bucket" {`

**LAB rce_web_app** 
`[cloudgoat] terraform init completed with no error code.
╷
│ Error: only alphanumeric characters and hyphens allowed in "name": "cg-lb-rce_web_app_cgid8lfijuwyg9"
│
│   with aws_lb.cg-lb,
│   on lb.tf line 28, in resource "aws_lb" "cg-lb":
│   28:   name = "cg-lb-${var.cgid}"
│
╵
╷
│ Error: "name" cannot be longer than 32 characters
│
│   with aws_lb_target_group.cg-target-group,
│   on lb.tf line 52, in resource "aws_lb_target_group" "cg-target-group":
│   52:   name = "cg-target-group-${var.cgid}"
│
╵
╷
│ Error: only alphanumeric characters and hyphens allowed in "name"
│
│   with aws_lb_target_group.cg-target-group,
│   on lb.tf line 52, in resource "aws_lb_target_group" "cg-target-group":
│   52:   name = "cg-target-group-${var.cgid}"
│
╵
╷
│ Error: only lowercase alphanumeric characters and hyphens allowed in "identifier"
│
│   with aws_db_instance.cg-psql-rds,
│   on rds.tf line 47, in resource "aws_db_instance" "cg-psql-rds":
│   47:   identifier = "cg-rds-instance-${var.cgid}"`

**Comment by christophetd** [comment]
Same issue for `cloud_breach_s3`.
