### ISSUE TITLE
hi bro 

### ISSUE THREAD

**Issue by koreatlwls** [RhinoSecurityLabs/cloudgoat#105]
I want to create codebuild_secrets 
but
Error: only lowercase alphanumeric characters and hyphens allowed in "identifier"
│ 
│   with aws_db_instance.cg-psql-rds,
│   on rds.tf line 51, in resource "aws_db_instance" "cg-psql-rds":
│   51:   identifier = "cg-rds-instance-${var.cgid}"
│ 
╵

[cloudgoat] Error while running `terraform plan`.
    exit code: 1
    stdout: None
    stderr: None

this error happen 
how to solve this error ??

**Comment by RyanJarv** [comment]
Just merged #106, if you want to try pulling the latest commit from master let us know if that resolves the issue for you. Thanks!
