### ISSUE TITLE
unintended vulnerability in Scenario: ecs_efs_attack

### ISSUE THREAD

**Issue by 1nteger-c** [RhinoSecurityLabs/cloudgoat#107]
I found some unintended way to get the flag of the "ecs_efs_attack". 
But  I think it must be patched so I write the issue about this vulnerability.

After command `$ ./cloudgoat.py create ecs_efs_attack` , I can access to the EC2 instance by using the given private key. 
In that situation, I tried to mount EFS data.  When I tried to mount, some error occur but I can solve that error by install nfs package. 
`$ sudo apt-get install nfs-common`
After that, I can mount the data and I can see the flag.

**Comment by andrew-aiken** [comment]
Created a PR #220  to fix the issue you described.

Moved the initial server into another subnet. Whitelisted the EFS security group to only allow mounts from the subnet with the "admin" EC2 instance.
