### ISSUE TITLE
Error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.

### ISSUE THREAD

**Issue by javalogicuser** [RhinoSecurityLabs/cloudgoat#108]
Not able to do any of these challenges because of the AWS provider error, using Kali...

Currently trying the iam_privesc_by_rollback...

I've set/used environment variables for the AWS credentials; tried to use the credentials file; I've verified the access keys work; but still getting the error:
│ 
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│       For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│ 
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 1, in provider "aws":
│    1: provider "aws" {
│ 
╵

[cloudgoat] Error while running `terraform plan`.
    exit code: 1
    stdout: None
    stderr: None

└─$ cat credentials 
[cloudgoat]
aws_access_key_id = 123123123132123132
aws_secret_access_key = <someRandomStringskeys>
region = us-east-1
role_arn = arn:aws:iam::123123123123:user/cloudgoat
source_profile = default
[default]
aws_access_key_id = 123123123132123132
aws_secret_access_key =<someRandomStringskeys>

I even tried to modify the provider.tf file for the specific scenario:
└─$ cat /opt/cloudgoat/scenarios/iam_privesc_by_rollback/terraform/provider.tf                                                                                                                      254 ⨯
provider "aws" {
  profile = "cloudgoat"
  region = "${var.region}"
}
  
Not sure what else I can do to get this to work.....

**Comment by htoochonaung** [comment]
Me too . I face with that kinda error

**Comment by 7absec** [comment]
Execute the following code

export AWS_ACCESS_KEY_ID="xxxxxxxxxxxxx" 
export AWS_SECRET_ACCESS_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxx" 
export AWS_DEFAULT_REGION="your-region-1"
