### ISSUE TITLE
Multiple scenarios are not working on terraform-provider-aws v4.0

### ISSUE THREAD

**Issue by SieBrum** [RhinoSecurityLabs/cloudgoat#119]
All scenarios that use 
`
ACL: private
`
Are now failing using the newest [terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws) version, as the `acl` has been deprecated (it says it's deprecated but the script now fails to deploy anything so it seems to be fully removed).

> resource/aws_s3_bucket: The acl and grant arguments have been deprecated and are now read-only. Use the aws_s3_bucket_acl resource instead

`
The some of the affected scenarios are (but not limited to):
- cloud_breach_s3
- rce_web_app

**Comment by cmd-ctrl-freq** [comment]
@SieBrum Thanks for bringing this issue up. I'm actually working on cloudgoat today so I'll take a look at this.

**Comment by cmd-ctrl-freq** [comment]
@SieBrum I just pushed a hotfix for this issue to master. Thanks for bring this up! Please let me know if you run into future issues.
