### ISSUE TITLE
S3.tf is having issue in acl="private"

### ISSUE THREAD

**Issue by benedictkwok** [RhinoSecurityLabs/cloudgoat#124]
./cloudgoat.py create ec2_ssrf
The create command requires the use of the --profile flag, or a default profile defined in the config.yml file (try "config profile").
bash-5.1# ./cloudgoat.py create ec2_ssrf --profile default
No whitelist.txt file was found at /usr/src/cloudgoat/whitelist.txt
CloudGoat can automatically make a network request, using curl, to ifconfig.co to find your IP address, and then create the whitelist file with the result.
Would you like to continue? [y/n]: y

whitelist.txt created with IP address XXX.XXX.XXX.XXX/32

Now running ec2_ssrf's start.sh...

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/archive...
- Finding latest version of hashicorp/aws...
- Finding latest version of hashicorp/null...
- Installing hashicorp/null v3.1.1...
- Installed hashicorp/null v3.1.1 (signed by HashiCorp)
- Installing hashicorp/archive v2.2.0...
- Installed hashicorp/archive v2.2.0 (signed by HashiCorp)
- Installing hashicorp/aws v4.8.0...
- Installed hashicorp/aws v4.8.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
[cloudgoat] terraform init completed with no error code.
╷
│ Error: Value for unconfigurable attribute
│ 
│   with aws_s3_bucket.cg-secret-s3-bucket,
│   on s3.tf line 4, in resource "aws_s3_bucket" "cg-secret-s3-bucket":
│    4:   acl = "private"
│ 
│ Can't configure a value for "acl": its value will be decided automatically based on the result of applying this configuration.

**Comment by jdearmas** [comment]
Hi benedictkwok,

Thank you for reporting the issue. I've checked the latest commit on the main branch (at time of writing: 8477f00), and it seems that the problem is no longer present there. Therefore, I suggest trying again with the latest version. 

If you still encounter the same issue even after testing on the latest commit, please let me know, and we'll investigate it further together.

Kind regards,
John
