### ISSUE TITLE
Not letting me destroy 

### ISSUE THREAD

**Issue by ArtistYay** [RhinoSecurityLabs/cloudgoat#130]
![image](https://user-images.githubusercontent.com/72479678/169102138-4b053844-ce9c-4f50-95c7-e105d8c855e7.png)

Not sure what's missing, I'm a beginner in this.

**Comment by RyanJarv** [comment]
This should also be resolved with https://github.com/RhinoSecurityLabs/cloudgoat/pull/129 merged.

I'm going to close this for now, but if anyone is running into issues on the latest commit let me know.
