### ISSUE TITLE
Step 5: assume the lambda invoker role 

### ISSUE THREAD

**Issue by ArtistYay** [RhinoSecurityLabs/cloudgoat#131]
![image](https://user-images.githubusercontent.com/72479678/169104403-225ae737-7c51-4bdf-a795-b5b8c01973c2.png)

I've posted in the slack channel also but haven't gotten any help. Between this and destroy the scenario I'm having trouble.

**Comment by RyanJarv** [comment]
Hey @ArtistYay looks like there are quotes missing around the last element (cg-... should be "cg-...").

**Comment by RyanJarv** [comment]
It looks like we'll have to clarify this in the cheat sheet. Right now it attempts to show where to replace the real name but doesn't say much about quoting to make it valid JSON.

**Comment by RyanJarv** [comment]
Can you try again with double quotes instead of single?

**Comment by ArtistYay** [comment]
> Can you try again with double quotes instead of single?
> 
> Or let me know if you where using double quotes, may have to dig into this more if that's the case.

Yeah I had double quotes in the command. Not sure why the out txt is showing single.

**Comment by ArtistYay** [comment]
> 

Hey I used the double quotes and this is what I got. 
![image](https://user-images.githubusercontent.com/72479678/173396323-4de05517-d9a6-418b-8c33-dece14525421.png)

**Comment by jdearmas** [comment]
Hello @ArtistYay,

The error in the screenshot that you've provide can provide enlightenment and resolution to the situation. 
It states that the parameter 'Username' (user_name) is **the wrong type** (invalid type). 

The type you provided was a <class 'list'>. 
The type expected was a <class 'str'> (aka a string). 

The solution is simply to remove the square brackets:
  From:
`["cg-bilbo-vulnerable_lambda_cgid7gzbz4dy6s"]`
  To:
`"cg-bilbo-vulnerable_lambda_cgid7gzbz4dy6s"`

I recommend watching @TeneBrae93's [video walk-through](https://www.youtube.com/watch?v=6NV3F6mDpGs&list=PLMoaZm9nyKaNRN0SoR_PBVYc_RAhbZdG4&index=3) of the scenario.

Here's a screenshot from the video:
![image](https://user-images.githubusercontent.com/29385551/232178071-e86e3c96-71d1-4b9c-a7e1-e5b3a896a9ec.png)
