### ISSUE TITLE
enhancement: address multi-tenancy issues with session ids for generated resources

### ISSUE THREAD

**Issue by kbroughton** [RhinoSecurityLabs/cloudgoat#14]
I'm showing cloudgoat to some colleagues and we are using a company AWS org.
The multitenancy desired is:
shared AWS org
separate cloudgoat envs per user

This causes some problems:

cloudgoat_key is created once by the first user and others don't have access to the private key
 - workaround: choose a distinct region for the second user to upload a key to
- fix: have the cloudgoat_key read from ~/.ssh/rsa and create a session id
   cloudgoat_key-12345

administrator user is generated by the first user.  Subsequent users don't have the pwd.
- workaround: share the admin user pwd
- fix: generate a session suffix for administrator-12345 at terraform plan time.

Same issue for joe and bob users.

**Comment by rhino-xander** [comment]
Hey! These issue should be gone with the release of 2.0. Enjoy!
