### ISSUE TITLE
Missing security group in EC2 instance

### ISSUE THREAD

**Issue by xep624** [RhinoSecurityLabs/cloudgoat#15]
Hi guys! 

I see that after deploying the Cloadgoat, the EC2 instance has only "cloudgoat_ec2_sg" security group assigned, what allows only for inbound SSH traffic. I guess it should also be assigned to "cloudgoat_lb_sg" group to allow for HTTP traffic by default.

P.S.
But also have to say that (at least so far) Cloudgoat works like a charm and I really enjoy it - awesome job guys!

**Comment by SpenGietz** [comment]
Hey, glad you are enjoying it!

The EC2 instance is only given inbound access over SSH on purpose, as part of CloudGoat is figuring out a way to open that port on that instance, so you can access the web server. 

It tries to simulate a scenario where a certain port is white-listed to an IP that isn't yours, or potentially a webapp that is meant to be accessible from localhost only, but happens to be listening on 0.0.0.0.

<details> 
  <summary>SPOILER: Here is the solution to that particular case</summary>
- Use the EC2 permission ModifyInstanceAttribute to change the security group associated with the EC2 instance to `cloudgoat_ec2_debug_sg` or `cloudgoat_lb_sg`.
</details>

I'm going to close this for now, but let me know/re-open if you have any other questions!
