### ISSUE TITLE
cloud_breach_s3 Connection refused

### ISSUE THREAD

**Issue by GSkouroupathis** [RhinoSecurityLabs/cloudgoat#179]
Hey, after successfully creating the cloud_breach_s3 scenario, I'm trying to connect to the reverse proxy with curl but I get the following error:

`curl: (7) Failed to connect to XXX port 80 after 2208 ms: Connection refused.`

Anyone else experiencing this issue?

**Comment by jdearmas** [comment]
I've **successfully** curled the EC2 instances of the **cloud_breach_s3 scenario** on commit e0338d9cd6f66206d0d053b3ee50635ab23ec4f9. 

What git commit hash are you using?

The '-v' flag increases the verbosity of the curl command. 

Can you run the command with the '-v' flag and share the output?

**Comment by GSkouroupathis** [comment]
Hey, I believe I'm having this issue https://repost.aws/questions/QUIrlxErTGSxesqwaawWBb-g/questions/QUIrlxErTGSxesqwaawWBb-g/ssh-into-ec2-stops-accepting-connections-after-about-8-minutes, so I'm waiting from Amazon to fix it on their side.
I think this can close now, thank you.
