### ISSUE TITLE
Platform Error on Mac M1

### ISSUE THREAD

**Issue by pabz616** [RhinoSecurityLabs/cloudgoat#180]
**Description**
Encountered the following error during CloudGoat environment setup
`WARNING: The requested image's platform (linux/amd64/) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Commit**
[e0338d9](https://github.com/RhinoSecurityLabs/cloudgoat/commit/e0338d9cd6f66206d0d053b3ee50635ab23ec4f9)

**System**
Mac M1, running Ventura 13.3

**Steps**
1. Completed initial steps of installing CloudGoat on my machine
2. Completed docker setup
3. I cloned the repo and followed the steps in the README

**Expected Result**
* Works as expected

**Actual Result**
* After I launched docker, I ran $ docker run -it rhinosecuritylabs/cloudgoat:latest and got the following error:
<img width="1430" alt="Screenshot 2023-04-04 at 11 46 35 AM" src="https://user-images.githubusercontent.com/22268013/229901511-b8f84026-61ae-43c4-9ec4-9af723d21d7c.png">
(apologies for the quality of the image, this is not cropped)

**Workaround**
I repeated the steps in my Kali Linux VM and got different errors, unrelated to this (separate ticket)

**Comment by DaveYesland** [comment]
Could you try this pull request which may fix this issue?: https://github.com/RhinoSecurityLabs/cloudgoat/pull/123

```
cd cloudgoat
git fetch origin pull/123/head:bug/docker-fix-non-amd64
git checkout bug/docker-fix-non-amd64
```
Then attempt to go through the setup and steps to reproduce your issue.

**Comment by pabz616** [comment]
@DaveYesland - no luck; same error. I've seen this type of error before and it has something to do with the Docker yml file, but I can't seem to locate `linux/amd64` anywhere.

**Comment by jdearmas** [comment]
@pabz616 

Although the root cause is still under investigation. A potential work-a-round has been discovered. Let me know if this works for you!

**The steps of the work-a-round:**

1. Download the cloudgoat git repository.

    `git clone https://github.com/RhinoSecurityLabs/cloudgoat`
    `cd cloudgoat`

2. Build the cloudgoat Docker Image, locally.

    `docker build -t cloudgoat .`

3. Run the local cloudgoat docker image as a container.

    `docker run -it cloudgoat`
    
**Testing Environment**
Mac M1

**Comment by pabz616** [comment]
Yatzee! No errors for building the app
![Screenshot 2023-04-05 at 3 35 59 PM](https://user-images.githubusercontent.com/22268013/230186418-a86fa8ff-8ee5-4d3a-83e3-e949cd6af2b3.png)
