### ISSUE TITLE
file provisioner error: i/o timeout

### ISSUE THREAD

**Issue by nobodynate** [RhinoSecurityLabs/cloudgoat#182]
[Discord Thread](https://discord.com/channels/969671994599669760/1074135870753488906/1096397611210125342)

On a newly installed environment, when trying to deploy the rce_web_app scenario, a user got the following errors:
![image](https://user-images.githubusercontent.com/77979206/232080623-6c2729dc-26ca-4d21-99c1-b16ce9ee570e.png)

According to [terraform aws provider docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object) `aws_s3_bucket_object` has been deprecated in favor of the `aws_s3_object` and will be removed in a future version (though I can't find which version).

The scenario successfully deploys in a docker container with Terraform 1.3.9.

**Comment by nobodynate** [comment]
With terraform 1.4.5 and aws-cli/2.11.12 I was able to deploy this without error. The deprecated warning still appears, but I get the success message instead of file provisioner error.

> Apply complete! Resources: 48 added, 0 changed, 0 destroyed.

Now I think the actual issue is the i/o timeout error. Maybe this is just an issue on the user's network configuration?

**Comment by adiveli** [comment]
Hi everyone, I am still getting the timeout error :(
<img width="546" alt="Screenshot 2024-01-15 at 18 25 39" src="https://github.com/RhinoSecurityLabs/cloudgoat/assets/16647714/439c46f4-8008-4731-97ca-8dbdacea1044">

AWS CLI version: aws-cli/2.15.6 Python/3.11.6 Darwin/23.1.0 exe/x86_64 prompt/off
Terraform: Terraform v1.6.6

Is there any fix for this?

**Comment by andrew-aiken** [comment]
@adiveli 

Could you public IP have changed?
If you look in the `whitelist.txt` does it differ than what you get from running `curl ifconfig.me`?


You can also try seeing if the port is open
```bash
nmap -T4 -Pn -p 22 54.198.184.232
```

**Comment by adiveli** [comment]
@andrew-aiken I have reissued : config whitelist --auto ; and now it seems to work. Thanks a lot for your help 🫡
