### ISSUE TITLE
vulnerable_cognito setup issue

### ISSUE THREAD

**Issue by Anomia2** [RhinoSecurityLabs/cloudgoat#187]
I get the  error below when running ./cloudgoat.py create vulnerable_cognito. AdministratorAccess is granted to the "cloudgoat" user as instructed for the setup; and I've tried giving the user  "AmazonS3FullAccess" (https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonS3FullAccess.html) permissions as well with no success.

│ Error: Error putting S3 policy: AccessDenied: Access Denied
│       status code: 403, request id: [ID], host id: [host id]
│ 
│   with aws_s3_bucket_policy.allow_access_from_another_account,
│   on s3.tf line 13, in resource "aws_s3_bucket_policy" "allow_access_from_another_account":
│   13: resource "aws_s3_bucket_policy" "allow_access_from_another_account" {
│ 

[cloudgoat] Error while running `terraform apply`.
    exit code: 1
    stdout: None
    stderr: None

**Comment by cipa5** [comment]
In order to solve this issue, first you can watch my [video](https://youtu.be/ozBOeqCJmYM) and follow exactly the same steps, then you need to delete cognito and re-create scenario, please let me know if i can help somehow, feel free to PM me.

**Comment by chryzsh** [comment]
I encountered the same issue, so thank you for the video, which fixed it. To recap:

- Navigate to the S3 bucket
- Go to the permissions tab
- Turn OFF "Block all public access"
- Scroll down to Object ownership, and change to ACLs enabled, click "Save changes"
- Now edit the ACL and check "Read" for "Everyone (public access) and "I understand the effects..
- Save changes and run the cloudgoat command again

**Screenshots**
![image](https://github.com/RhinoSecurityLabs/cloudgoat/assets/2836099/177bfb21-65ec-4120-a9d6-785b542fbbb7)
![image](https://github.com/RhinoSecurityLabs/cloudgoat/assets/2836099/526bbde5-5c0f-4a70-917e-4436fc47d482)
![image](https://github.com/RhinoSecurityLabs/cloudgoat/assets/2836099/000602d5-9fd1-4d83-9597-808331e9eba4)

**Comment by cipa5** [comment]
> I encountered the same issue, so thank you for the video, which fixed it. To recap:
> 
> * Navigate to the S3 bucket
> * Go to the permissions tab
> * Turn OFF "Block all public access"
> * Scroll down to Object ownership, and change to ACLs enabled, click "Save changes"
> * Now edit the ACL and check "Read" for "Everyone (public access) and "I understand the effects..
> * Save changes and run the cloudgoat command again
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/2836099/250455070-177bfb21-65ec-4120-a9d6-785b542fbbb7.png) ![image](https://user-images.githubusercontent.com/2836099/250454961-526bbde5-5c0f-4a70-917e-4436fc47d482.png) ![image](https://user-images.githubusercontent.com/2836099/250456262-000602d5-9fd1-4d83-9597-808331e9eba4.png)

No problem, I am glad it helped! Perfect recap!

**Comment by Anomia2** [comment]
This worked but I also had to delete the User Pool within Amazon Cognito prior to re-running [./cloudgoat.py create vulnerable_cognito].

**Comment by cipa5** [comment]
> This worked but I also had to delete the User Pool within Amazon Cognito prior to re-running [./cloudgoat.py create vulnerable_cognito].

Yes, that is needed as well, I forget to mention it. Good point!
