### ISSUE TITLE
Failure to Create ECS Takeover Scenario

### ISSUE THREAD

**Issue by mr-b4rt0wsk1** [RhinoSecurityLabs/cloudgoat#191]
Running `./cloudgoat.py create ecs_takeover` fails with the following error:

![Screenshot 2023-05-24 at 9 30 47 AM](https://github.com/RhinoSecurityLabs/cloudgoat/assets/98570190/01462433-4578-4f27-9dc1-ce64036e85a4)

It looks like the cause is that the AMI value referenced in the `scenarios/ecs_takeover/terraform/ec2.tf` file is no longer valid:

![Screenshot 2023-05-24 at 9 36 49 AM](https://github.com/RhinoSecurityLabs/cloudgoat/assets/98570190/dc161a45-70ac-40c7-80f6-af01fbb4b5a0)

**Comment by maddsec** [comment]
same here
