### ISSUE TITLE
User Data not applied on first boot - instance unreachable via SSH and HTTP

### ISSUE THREAD

**Issue by lukasz-vsl** [RhinoSecurityLabs/cloudgoat#20]
When creating the environment with ./start.sh <ip-here> it runs as intended however the instance is later unreachable as the User-Data is not executed on the created instance. It required the instance to be rebooted, which then executed UserData as intended.

This was verified by removing `#cloud-boothook` from ec2.tf file, which will cause User data to execute on initial launch instead of every-other reboot.

**Comment by LukaszMrozowski** [comment]
On that note, in future uses of #21 the boothook comment would not allow instance to boot properly and it would remain unavailable. To inject bash scripts via CloudInit, use [https://aws.amazon.com/premiumsupport/knowledge-center/execute-user-data-ec2/](url). Worked like a charm.
