### ISSUE TITLE
cicd : ssm connection and scenario deletion 

### ISSUE THREAD

**Issue by Anomia2** [RhinoSecurityLabs/cloudgoat#200]
After adding tags to the EC2 instance on "cicd" as needed, I get the following error code when trying to start the ssm-session. The session won't start. The command and response is below.

aws ssm start-session --target [instance] --region us-east-1 --profile [profile]

An error occurred (TargetNotConnected) when calling the StartSession operation: i-0bc181d6dfb0a07b2 is not connected.

**Comment by cipa5** [comment]
I believe you need to manually log in into AWS profile that you are using for cloudgoat and delete whatever ECR repo has in there and after that you can delete it. If you see the error it says  RepositoryNotEmpty.

**Comment by Anomia2** [comment]
> I believe you need to manually log in into AWS profile that you are using for cloudgoat and delete whatever ECR repo has in there and after that you can delete it. If you see the error it says  RepositoryNotEmpty.

This worked I just brought it up in case it wasn't working as intended.

**Comment by cipa5** [comment]
Ohh, got it! Thank you for that.
