### ISSUE TITLE
detection_evasion : ssm connection and git clone issue

### ISSUE THREAD

**Issue by Anomia2** [RhinoSecurityLabs/cloudgoat#202]
I'm unable to start an ssm session with the instance with the instance for the "easy path". I was able to connect to the instance for the "hard path" but unable to git clone the repository for the resources.

Easy path (unable to connect via sim)
<img width="966" alt="Pasted Graphic" src="https://github.com/RhinoSecurityLabs/cloudgoat/assets/86126929/79b6b240-7c75-47a0-bbbd-35d01edc1ed2">

Solution for hard path doesn’t work.
<img width="960" alt="Pasted Graphic 1" src="https://github.com/RhinoSecurityLabs/cloudgoat/assets/86126929/5d49189e-2750-4a4e-a92f-018c383ff2e6">

**Comment by cipa5** [comment]
Same here, please PM me if you find out any solutions, been fighting with this one for 2 days now. Thank you!

**Comment by andrew-aiken** [comment]
It looks like the GH repo does not exist (or private)

There also seems to be issues with the module putting the internet gateway on another VPC

**Comment by andrew-aiken** [comment]
Have a fix for the issue with internet on the easy EC2 server
https://github.com/RhinoSecurityLabs/cloudgoat/pull/218

**Comment by jdearmas** [comment]
Fixed in commit 1bc18b8

Thanks to #218.
