### ISSUE TITLE
Problem creating ec2 instance on ecs_takeover

### ISSUE THREAD

**Issue by arbaaz-a** [RhinoSecurityLabs/cloudgoat#205]
When I run the terraform, it runs on an issue for the ec2 instances saying the boot type does not match. I edited the terraform code so it finds an AMI that works. However, when I run terraform destroy it doesnt destroy all the resources properly. Any suggestions?

**Comment by muratBekgi** [comment]
Had the same issue where I had to modify the ec2.tf file to create the resources, but when trying to destroy the resources after, it goes into a loop. Easy fix is to delete the 2 created EC2 instances and ECS container manually, and then re-run ./cloudgoat.py destroy ecs_takeover

> When I run the terraform, it runs on an issue for the ec2 instances saying the boot type does not match. I edited the terraform code so it finds an AMI that works. However, when I run terraform destroy it doesnt destroy all the resources properly. Any suggestions?

Had the same issue where I had to modify the ec2.tf file to create the resources, but when trying to destroy the resources after, it goes into a loop. Easy fix is to delete the 2 created EC2 instances and ECS container manually, and then re-run ./cloudgoat.py destroy ecs_takeover
