### ISSUE TITLE
ecs_takeover creation fail >>> FIX

### ISSUE THREAD

**Issue by muratBekgi** [RhinoSecurityLabs/cloudgoat#209]
EDIT:  cloudgoat>scenarios>ecs_takeover>terraform>ec2.tf

```
data "aws_ami" "ecs" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["amzn2-ami-ecs-hvm-*x86_64*"]  # Filter for x86_64 architecture AMIs
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

locals {
  user_data = <<EOH
#!/bin/bash
echo ECS_CLUSTER=${aws_ecs_cluster.ecs_cluster.name} >> /etc/ecs/ecs.config
EOH
}

resource "aws_instance" "vulnsite" {
  ami                         = data.aws_ami.ecs.id
  iam_instance_profile        = aws_iam_instance_profile.ecs_agent.name
  vpc_security_group_ids      = [aws_security_group.ecs_sg.id]
  user_data                   = local.user_data
  instance_type               = "t3.micro"  # Using t3.micro instance type
  associate_public_ip_address = true
  subnet_id                   = aws_subnet.public.id

  tags = {
    "Name" = "cg-${var.scenario-name}-${var.cgid}-vulnsite"
  }
}

resource "aws_instance" "vault" {
  ami                         = data.aws_ami.ecs.id
  iam_instance_profile        = aws_iam_instance_profile.ecs_agent.name
  vpc_security_group_ids      = [aws_security_group.ecs_sg.id]
  user_data                   = local.user_data
  instance_type               = "t3.micro"  # Using t3.micro instance type
  associate_public_ip_address = true
  subnet_id                   = aws_subnet.public.id

  tags = {
    "Name" = "cg-${var.scenario-name}-${var.cgid}-vault"
  }
}

```

**Comment by andrew-aiken** [comment]
What issue is this fixing?

**Comment by christophelimpalair** [comment]
> What issue is this fixing?

It fixes this issue:
```
╷
│ Error: creating EC2 Instance: InvalidParameterValue: The t2.micro instance type does not support an AMI with a boot mode of UEFI. Only instance types built on the Nitro System support UEFI. Specify an instance type that supports UEFI, and try again.
│ 	status code: 400, request id: 996fb7d6-045c-49aa-96f4-52f68fba9a9c
│ 
│   with aws_instance.vulnsite,
│   on ec2.tf line 23, in resource "aws_instance" "vulnsite":
│   23: resource "aws_instance" "vulnsite" {
│ 
╵
╷
│ Error: creating EC2 Instance: InvalidParameterValue: The t2.micro instance type does not support an AMI with a boot mode of UEFI. Only instance types built on the Nitro System support UEFI. Specify an instance type that supports UEFI, and try again.
│ 	status code: 400, request id: 89ddfd61-c26c-45b4-9acf-1597bda8a749
│ 
│   with aws_instance.vault,
│   on ec2.tf line 37, in resource "aws_instance" "vault":
│   37: resource "aws_instance" "vault" {
│ 
╵
```

**Comment by muratBekgi** [comment]
> 

This !
thank you

**Comment by muratBekgi** [comment]
> > What issue is this fixing?
> 
> It fixes this issue:
> 
> ```
> ╷
> │ Error: creating EC2 Instance: InvalidParameterValue: The t2.micro instance type does not support an AMI with a boot mode of UEFI. Only instance types built on the Nitro System support UEFI. Specify an instance type that supports UEFI, and try again.
> │ 	status code: 400, request id: 
> │ 
> │   with aws_instance.vulnsite,
> │   on ec2.tf line 23, in resource "aws_instance" "vulnsite":
> │   23: resource "aws_instance" "vulnsite" {
> │ 
> ╵
> ╷
> │ Error: creating EC2 Instance: InvalidParameterValue: The t2.micro instance type does not support an AMI with a boot mode of UEFI. Only instance types built on the Nitro System support UEFI. Specify an instance type that supports UEFI, and try again.
> │ 	status code: 400, request id: 
> │ 
> │   with aws_instance.vault,
> │   on ec2.tf line 37, in resource "aws_instance" "vault":
> │   37: resource "aws_instance" "vault" {
> │ 
> ╵
> ```

This ^^^
Thank you!

**Comment by andrew-aiken** [comment]
Do you know what `ami` it was using?
Its pulling the latest image and it can be for **arm64** which requires uefi. If I require it to be x86_64 it should still work with t2.micro

**Comment by muratBekgi** [comment]
> Do you know what `ami` it was using? Its pulling the latest image and it can be for **arm64** which requires uefi. If I require it to be x86_64 it should still work with t2.micro

Sorry I do not recall, but it is whatever you had in your original terraform files I believe

**Comment by andrew-aiken** [comment]
NP
Its probably an issue that only happens sometimes depending when AWS release a new AMI. Should be solved by  https://github.com/RhinoSecurityLabs/cloudgoat/pull/219
