### ISSUE TITLE
Why are most of the services not inside the VPC?

### ISSUE THREAD

**Issue by mfuellbier** [RhinoSecurityLabs/cloudgoat#22]
The EC2 Instance and the ELB are part of a VPC, but all the other services (s3, Lambda, Lightsail) are not. It would be nice to also have them displayed in [Cloudmapper](https://github.com/duo-labs/cloudmapper ), but Cloudmapper only displays instances with a VPN-Endpoint.

**Comment by mfuellbier** [comment]
Wouldn't it be nice to give the user the option to launch Cloudgoat in a custom VPC. This way, multiple Cloudgoats could be launched in parallel, each in its own VPC. This would be handy in an environment where multiple user share an AWS Account.

**Comment by rhino-xander** [comment]
Hey! These points should have been addressed quite handily in the 2.0 release.
