### ISSUE TITLE
Failing Installation - Credentials.txt Empty

### ISSUE THREAD

**Issue by leaustinwile** [RhinoSecurityLabs/cloudgoat#23]
I start off by running the below command:

`./start.sh 192.168.1.0/24`

I use my public IP and terraform appears to apply the changes fine, but then I get this error:
```
Apply complete! Resources: 39 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
Traceback (most recent call last):
  File "./extract_creds.py", line 10, in <module>
    encryptpass = data['modules'][0]['resources']['aws_iam_user_login_profile.administrator']['primary']['attributes']['encrypted_password']
KeyError: 'modules'
root@ubuntu:/opt/cloudgoat# 
```

I'm on the newest version of Ubuntu: 

```
root@ubuntu:/opt/cloudgoat# uname -a
Linux ubuntu 5.0.0-15-generic #16-Ubuntu SMP Mon May 6 17:41:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
So I really don't know what else to try other than downgrading and installing it from like a 14.04/16.04 box. Thoughts?

**Comment by rhino-xander** [comment]
Hey! This issue should be gone with the release of 2.0. Please let us know if you continue to have any issues.

**Comment by leaustinwile** [comment]
Awesome. FYI my AWS account has been banned as a result of attempting to
install cloudgoat incorrectly. You need to put a warning in your github
because they've decided it's irreversible.

**Comment by leaustinwile** [comment]
I tried installing it about 3 times, maybe 4 and they banned me with no
recourse that I could take.
