### ISSUE TITLE
Terraform not found when running CloudGoat on Kali Linux

### ISSUE THREAD

**Issue by DimitriosTsarouchas** [RhinoSecurityLabs/cloudgoat#251]
When attempting to run the `./cloudgoat.py` script on Kali Linux after following the installation steps provided on the Terraform website, I encountered the following error:
Terraform not found. Please install Terraform before using CloudGoat.

## Steps to Reproduce
1. Followed the instructions to install terraform on a Linux system from the Terraform website.
2. Ran the `./cloudgoat.py` script.
3. Received the "Terraform not found. Please install Terraform before using CloudGoat." error message.

## Environment Details
- Operating System: Kali Linux

**Comment by DaveYesland** [comment]
Can you run `terraform --version` outside of cloudgoat?

**Comment by DimitriosTsarouchas** [comment]
Here is the output of running `terraform --version`

`terraform --version`
Command 'terraform' not found, but can be installed with:
apt install terraform
Do you want to install it? (N/y)y
apt install terraform
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
terraform is already the newest version (1.6.3-0kali1).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.

**Comment by DaveYesland** [comment]
This looks to be an issue with your environment and terraform not being properly installed or setup. You will need to figure out what is going on with Terraform and make sure you can run it before cloudgoat will work.
I am going to close this for now as it is not an issue relating to Cloudgoat itself.

**Comment by andrew-aiken** [comment]
There is currently a PR open to fix this issue https://github.com/RhinoSecurityLabs/cloudgoat/pull/249

Alternativlty you can [download/install](https://developer.hashicorp.com/terraform/install) Terraform directly from HashiCorp
