### ISSUE TITLE
Error deploying ec2_takeover senario

### ISSUE THREAD

**Issue by researcher111** [RhinoSecurityLabs/cloudgoat#252]
Not sure what is wrong but I get the following error when deploying the ec2_takeover senario; 

```
Error: creating EC2 Instance: InvalidParameterValue: The t2.micro instance type does not support an AMI with a boot mode of UEFI. Only instance types built on the Nitro System support UEFI. Specify an instance type that supports UEFI, and try again.
│       status code: 400, request id:
│ 
│   with aws_instance.vulnsite,
│   on ec2.tf line 23, in resource "aws_instance" "vulnsite":
│   23: resource "aws_instance" "vulnsite" {
```

**Comment by andrew-aiken** [comment]
Could you please share the AMI that was being used

**Comment by andrew-aiken** [comment]
Do you have the latest version of the repository pulled?

From looking at the line where the error is occurring (23) its probably the version before the fix
https://github.com/RhinoSecurityLabs/cloudgoat/commits/master/scenarios/ecs_takeover/terraform/ec2.tf

**Comment by andrew-aiken** [comment]
@researcher111 Did this help solve your issue?

**Comment by researcher111** [comment]
yes, solved it. Thank you.

**Comment by TeneBrae93** [comment]
Thank you @andrew-aiken for helping resolve this!
