### ISSUE TITLE
Incorrect AWS CLI Command

### ISSUE THREAD

**Issue by thetestlabs** [RhinoSecurityLabs/cloudgoat#27]
In the Calrission cheat sheet [here](https://github.com/RhinoSecurityLabs/cloudgoat/blob/master/scenarios/codebuild_secrets/cheat_sheet_calrissian.md), one of the commands is wrong:

`aws describe-db-subnet-groups --profile Calrissian`

should be

`aws rds describe-db-subnet-groups --profile Calrissian`

**Comment by Rhino-JBAnderson** [comment]
Thanks so much for pointing that out. Fix pushed!
