### ISSUE TITLE
scenario iam_privesc_by_rollback / set-default-policy-version issue

### ISSUE THREAD

**Issue by garridor76** [RhinoSecurityLabs/cloudgoat#28]
After executing a `set-default-policy-version` API call against IAM, in order to change the default policy version from v1 to v2 and complete the scenario, I do not see any changes.

The response I get from the CLI is `aws-cli/1.16.19 Python/3.7.3 Darwin/18.6.0 botocore/1.12.9` and yet, when I list the policy versions, I still see v1 as the default.

`aws> iam list-policy-versions --policy-arn "arn:aws:iam::xxxxxxxxxx:policy/cg-raynor-policy" --profile goat1`

```
{
    "Versions": [
        {
            "VersionId": "v5",
            "IsDefaultVersion": false,
            "CreateDate": "2019-07-03T20:12:36Z"
        },
        {
            "VersionId": "v4",
            "IsDefaultVersion": false,
            "CreateDate": "2019-07-03T20:12:36Z"
        },
        {
            "VersionId": "v3",
            "IsDefaultVersion": false,
            "CreateDate": "2019-07-03T20:12:36Z"
        },
        {
            "VersionId": "v2",
            "IsDefaultVersion": false,
            "CreateDate": "2019-07-03T20:12:36Z"
        },
        {
            "VersionId": "v1",
            "IsDefaultVersion": true,
            "CreateDate": "2019-07-03T20:12:34Z"
        }
    ]
}
```
`aws> iam set-default-policy-version --policy-arn "arn:aws:iam::xxxxxxxxxx:policy/cg-raynor-policy" --version v2`
```
aws-cli/1.16.19 Python/3.7.3 Darwin/18.6.0 botocore/1.12.9
```

Re-listing the policy versions still indicates that the default is v1, and not v2 as I requested it be.
`aws> iam list-policy-versions --policy-arn "arn:aws:iam::115754076533:policy/cg-raynor-policy" --profile goat1`

```
{
    "Versions": [
        {
            "VersionId": "v5",
            "IsDefaultVersion": false,
            "CreateDate": "2019-07-03T20:12:36Z"
        },
        {
            "VersionId": "v4",
            "IsDefaultVersion": false,
            "CreateDate": "2019-07-03T20:12:36Z"
        },
        {
            "VersionId": "v3",
            "IsDefaultVersion": false,
            "CreateDate": "2019-07-03T20:12:36Z"
        },
        {
            "VersionId": "v2",
            "IsDefaultVersion": false,
            "CreateDate": "2019-07-03T20:12:36Z"
        },
        {
            "VersionId": "v1",
            "IsDefaultVersion": true,
            "CreateDate": "2019-07-03T20:12:34Z"
        }
    ]
}
```
Checked CloudTrail logs for all actions by the public key of this user, and there are not calls logged outside of List and Get API calls.

Perhaps this functionality has been removed and this scenario is no longer applicable?

**Comment by rhino-xander** [comment]
Hey @garridor76 - really appreciate you trying out CloudGoat, and I'm sorry you seem to have run into trouble.

Luckily, I have the solution for you:  `--version` is the command to print the AWS CLI's version, which is what you're seeing. It seems that it will override everything else in the command.

If you try the command with `--version-id`, it should work properly.

Let me know if this solved your issue!

**Comment by garridor76** [comment]
duh!.  `--version-id` it is.  My bad, user error using aws-shell.
Thanks!
