### ISSUE TITLE
detection_evasion: There is issue on sdb:ListDomain action 

### ISSUE THREAD

**Issue by mahaputrailhamawal** [RhinoSecurityLabs/cloudgoat#283]
Hi @andrew-aiken. and @TeneBrae93. I had a problem running the first command on the easy path. I am experiencing an issue with sdb:ListDomains. As far as I remember the Simple DB service has been deprecated. Is this scenario still workable when SimpleDB has been deprecated?

<img width="850" alt="image" src="https://github.com/user-attachments/assets/4b91e0f1-c2fa-4a19-8320-dd77110261e9">

**Comment by andrew-aiken** [comment]
That service does not exist in the scenario.
Its there to get the ARN of the user without logging to CloudTrail.

> There are services which do not log to CloudTrail. Honeytokens almost never grant permissions to ANY services, let alone these services which do not log to CloudTrail. Thus ,the call below will fail for a honeytoken, but will reveal the ARN of the principal associated with the credentials. This information is usually sufficient to infer if the principal is only being used for honeytokens.

**Comment by mahaputrailhamawal** [comment]
If the SimpleDB service is not present in this scenario, then why in the first instruction in the cheatsheet do we call the sdb:ListDomain action?

**Comment by mahaputrailhamawal** [comment]
Oh i see. Thanks for the information.
