### ISSUE TITLE
detection_evasion: git clone issue (hard path)

### ISSUE THREAD

**Issue by mahaputrailhamawal** [RhinoSecurityLabs/cloudgoat#284]
Hi @andrew-aiken and @TeneBrae93. I have issues and confusion when working on hard paths. Which one is correct? Is the clone repo in the session manager or clone the repo locally? or is there another way to do the hard path?

I've tried cloning the hard path repo in two areas. When I tried to clone the repo in the session manager, I experienced an issue because git command was not installed. When I tried to install git command I realized that the hard path instance did not have access to the internet.
<img width="841" alt="image" src="https://github.com/user-attachments/assets/55896313-9128-4a17-948f-21b96b46ca80">

When I tried to clone the hard path repo to local, I also experienced problems like this.
<img width="847" alt="image" src="https://github.com/user-attachments/assets/099f38f3-3a06-4322-9306-b675522f81d9">

**Comment by andrew-aiken** [comment]
It looks like the GitHub repository does not exist or is privated.
I'll reach out to the Rhino team to see if it exists.
