### ISSUE TITLE
CloudGoat requires Python 3.6+ to run (Windows with Python 3.7.2)

### ISSUE THREAD

**Issue by vizzdoom** [RhinoSecurityLabs/cloudgoat#29]
Observed on Win10 1903 with Python 3.7:
```
PS D:\cloudgoat> .\cloudgoat.py config whitelist
CloudGoat requires Python 3.6+ to run.
PS D:\cloudgoat> python --version
Python 3.7.2
```

**Comment by rhino-xander** [comment]
Hey @vizzdoom - appreciate you taking CloudGoat for a spin. Unfortunately, the project doesn't support windows at this time. That said, we are working on adding docker support, which should make it easier to run CloudGoat on Windows.

You can check it out here: https://github.com/RhinoSecurityLabs/cloudgoat/tree/feature/add-docker
