### ISSUE TITLE
Feature Request: Generalized 'CloudGoat' Tag for All Resources

### ISSUE THREAD

**Issue by kulinacs** [RhinoSecurityLabs/cloudgoat#34]
It would be great if resources created by CloudGoat included some tag like `application: cloudgoat` for filtering, cost allocation, etc.

**Comment by rhino-xander** [comment]
@kulinacs thanks for checking out CloudGoat.

If you don't mind, could you expand on your idea a bit?

We already tag resources with the unique ID of the scenario instance. For example:

https://github.com/RhinoSecurityLabs/cloudgoat/blob/master/scenarios/cloud_breach_s3/terraform/ec2.tf
```
...
tags = {
    Name = "cg-ec2-http-${var.cgid}"
  }
...
```

Were you thinking of something more general, like a `CloudGoat` tag applied to all resources regardless of type and scenario?

**Comment by kulinacs** [comment]
Yeah, I was thinking of something more general. It could be as simple as:
```
tags = {
    ...
    application = "cloudgoat"
 }
```

This would make it easier to do things like group CloudGoat resources together in the management console, filtering on the CLI, and [seeing how much you've spent using CloudGoat](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/activating-tags.html).

**Comment by rhino-xander** [comment]
@kulinacs love it. I've added the idea to our team's internal product board. I'm not sure when we'll have time to implement this, so I'll leave this ticket open as well - just in case someone in the community wants to take this on.

**Comment by rhino-xander** [comment]
@kulinacs thanks to the hero of the hour ( @yogisec ) this has been added to CloudGoat. Enjoy!
