### ISSUE TITLE
rce_web_app scenario 502 bad gateway

### ISSUE THREAD

**Issue by halfluke** [RhinoSecurityLabs/cloudgoat#48]
After some troubleshooting and creating and destroying multiple times, I found out that node.js on the ec2 instance was not started. Result: 502 bad gateway in browser when opening the elb url.
I connected via ssh by downloading cloudgoat private key from the related keystore bucket, I went to the home folder, unzipped app.zip, and run: node .
Not sure of the root cause.

**Comment by halfluke** [comment]
Investigated a little and clearly the unzip command in ec2.tf doesn't work (only for me?), I still have to check if there are other issues. 
        unzip app.zip -d ./app
        cd app
        node index.js &

**Comment by halfluke** [comment]
so, checked /var/log/cloud-init-output.log on the ec2 instance.
the user_data is pulled fine and the instance tries to execute the bash script, however, it looks like in ubuntu bionic apt-get upgrade needs to restart some services, and it stops on the prompt of which services you want to restart.
The fix is: add
echo '* libraries/restart-without-asking boolean true' | sudo debconf-set-selections
at the beginning of the user_data section of ec2.tf

I don't think a pull request is needed unless you want me to create it.

Cheers.

**Comment by seb1055** [comment]
This issue was fixed in #60. Thank you!
