### ISSUE TITLE
Same issue in ec2_ssrf scenario as in rce_web_app scenario

### ISSUE THREAD

**Issue by halfluke** [RhinoSecurityLabs/cloudgoat#50]
nodejs doesn't not start automatically without adding

        echo '* libraries/restart-without-asking boolean true' | debconf-set-selections

after     
user_data = <<-EOF
        #!/bin/bash

in ec2.tf file.

So basically you cannot access the web app and you cannot perform the ssrf.
Please fix because having to troubleshoot something that was supposed to work has already spoiled two scenarios for me, and possibly for other people.

Thanks

**Comment by seb1055** [comment]
These issues were fixed in #56 and #60. Thank you!
