### ISSUE TITLE
Unable to Clone CloudGoat

### ISSUE THREAD

**Issue by Nemesis66-7** [RhinoSecurityLabs/cloudgoat#52]
I am trying to install the Rhino Security Labs CloudGoat on my AWS Ubuntu 18.04 LTS Free-tier EC2 instance. I followed the directions for setting up an admin user and configuring the AWS CLI and also set up terraform v0.12 per the directions. I also configured my instance's security group to allow All traffic.

However, when I run the git clone command I get "Permission denied" error. See below for full output:

> sudo git clone git@github.com:RhinoSecurityLabs/cloudgoat.git ./CloudGoat
> Cloning into './CloudGoat'...
> The authenticity of host 'github.com (<ipv4>)' can't be established.
> RSA key fingerprint is SHA256:<RSA key fingerprint>.
> Are you sure you want to continue connecting (yes/no)? yes
> Warning: Permanently added 'github.com,<ipv4>' (RSA) to the list of known hosts.
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists

Do I need to associate an SSH key on GitHub to my account and if so how do I do that? I'm not sure what else to try at this point. Thanks.

**Comment by hamstah** [comment]
Hey
Use the Https version of the repo instead of the git one as it's a public repo you're not a maintainer of.
