### ISSUE TITLE
Suggested tweak to shepard role in ec2_ssrf

### ISSUE THREAD

**Issue by wu4f** [RhinoSecurityLabs/cloudgoat#54]
I believe in the last step of this level, the shepard role only needs 
"Action": [
                "lambda:Get*",
                "lambda:Invoke*",
                "lambda:List*"
            ],

Right now, it has full access.  
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "shepard",
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
https://github.com/RhinoSecurityLabs/cloudgoat/blob/master/scenarios/ec2_ssrf/terraform/iam.tf

This led to some unfortunate usage on my AWS account.

**Comment by RyanJarv** [comment]
I went ahead and made a PR with your suggested changes.

I also looked through this module as well to see if there was any issues with the whitelist configuration but didn't find any. Do you know if you may have used a broader whitelist during setup then necessary by chance or if your using a shared IP? This may explain how someone else got ahold of these keys if so.

**Comment by jdearmas** [comment]
This issue was solved but never closed. I shall put an end to it.
