### ISSUE TITLE
Error while running the  iam_privesc_by_rollback script 

### ISSUE THREAD

**Issue by monu11** [RhinoSecurityLabs/cloudgoat#55]
./cloudgoat.py --profile test create iam_privesc_by_rollback
Loading whitelist.txt...
A whitelist.txt file was found that contains at least one valid IP address or range.
You already have an instance of iam_privesc_by_rollback deployed. Do you want to destroy and recreate it (y) or cancel (n)? [y/n]: y

No terraform.tfstate file was found in the scenario instance's terraform directory, so "terraform destroy" will not be run.

Successfully destroyed iam_privesc_by_rollback_cgidqog4aruu76.
Scenario instance files have been moved to /home/ubuntu/cloudgoat/trash/iam_privesc_by_rollback_cgidqog4aruu76
Usage: terraform init [options] [DIR]

  Initialize a new or existing Terraform working directory by creating
  initial files, loading any remote state, downloading modules, etc.

  This is the first command that should be run for any new or existing
  Terraform configuration per machine. This sets up all the local data
  necessary to run Terraform that is typically not committed to version
  control.

  This command is always safe to run multiple times. Though subsequent runs
  may give errors, this command will never delete your configuration or
  state. Even so, if you have important information, please back it up prior
  to running this command, just in case.

  If no arguments are given, the configuration in this working directory
  is initialized.

Options:

  -backend=true        Configure the backend for this configuration.

  -backend-config=path This can be either a path to an HCL file with key/value
                       assignments (same format as terraform.tfvars) or a
                       'key=value' format. This is merged with what is in the
                       configuration file. This can be specified multiple
                       times. The backend type must be in the configuration
                       itself.

  -force-copy          Suppress prompts about copying state data. This is
                       equivalent to providing a "yes" to all confirmation
                       prompts.

  -from-module=SOURCE  Copy the contents of the given module into the target
                       directory before initialization.

  -get=true            Download any modules for this configuration.

  -get-plugins=true    Download any missing plugins for this configuration.

  -input=true          Ask for input if necessary. If false, will error if
                       input was required.

  -lock=true           Lock the state file when locking is supported.

  -lock-timeout=0s     Duration to retry a state lock.

  -no-color            If specified, output won't contain any color.

  -plugin-dir          Directory containing plugin binaries. This overrides all
                       default search paths for plugins, and prevents the 
                       automatic installation of plugins. This flag can be used
                       multiple times.

  -reconfigure         Reconfigure the backend, ignoring any saved
                       configuration.

  -upgrade=false       If installing modules (-get) or plugins (-get-plugins),
                       ignore previously-downloaded objects and install the
                       latest version allowed within configured constraints.

  -verify-plugins=true Verify the authenticity and integrity of automatically
                       downloaded plugins.

[cloudgoat] Error while running `terraform init`.
    exit code: 1
    stdout: None
    stderr: None

Terraform version = v0.12.23

**Comment by jasbroek** [comment]
It looks like you already had one deployed, but when destroying it could not find `terraform.tfstate` and hence could not destroy properly. Did you deploy and perhaps removed the directory manually?
Double check in your AWS account for any left-over resources (after destroying the scenario).

The scenario deploys without issues on my side, if your issues persists, try a fresh clone of the repository (e.g delete current CloudGoat folder and clone this repository again).

**Comment by RyanJarv** [comment]
I'm going to go ahead and close this issue. If you're still having issues with this feel free to open another issue referencing this one.
