### ISSUE TITLE
in Ec2_ssrf not able to connect to http://ecipinstance

### ISSUE THREAD

**Issue by aries20** [RhinoSecurityLabs/cloudgoat#58]
Page Unable to connect

Firefox can’t establish a connection to the server at ec2-3-XXXXXXXX.compute-1.amazonaws.com.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by seb1055** [comment]
This was closed in pull request #56. I will be closing this now thank you!
