### ISSUE TITLE
Unable to run "./cloudgoat.py config profile"

### ISSUE THREAD

**Issue by rickgds80** [RhinoSecurityLabs/cloudgoat#74]
Hello I cloned the repository, I already installed all the requirements, but when running the configuration part I'm taking the following error:

root@kali:~/CloudGoat# ./cloudgoat.py config profile
**Traceback (most recent call last):
  File "./cloudgoat.py", line 112, in <module>
    from core.python.commands import CloudGoat
ModuleNotFoundError: No module named 'core.python'**

![image](https://user-images.githubusercontent.com/38327991/96805938-24c30380-13e9-11eb-9e4e-5135a9ab3ace.png)

Can you help me?

**Comment by sidejackthenativity** [comment]
Did you do the following?

pip3 install -r ./core/python/requirements.txt
$ chmod u+x cloudgoat.py

**Comment by rickgds80** [comment]
Yes, i've run the dependencies before.

![image](https://user-images.githubusercontent.com/38327991/97644235-8c500300-1a28-11eb-9108-9658ad84114d.png)

**Comment by blacklat** [comment]
this is a crap

**Comment by RyanJarv** [comment]
@rickgds80 Realize this is an old issue, but if you're still having issues with this do you mind posting the python version you're using?

At some point I believe python (unsure what versions) required __init__.py files in each directory of a module, which don't exist in this repo currently. If you're using an older python version upgrading may fix the issue.

**Comment by RyanJarv** [comment]
I'm going to close this issue. Feel free to open another one and reference this though if you are still having issues.

**Comment by YorkshireGold** [comment]
Hey @RyanJarv. I have this same issue, but don't want to clog things up with a duplicate.

 I tried all the obvious things; importing this package from different places, but it still isn't recognised, and I get the same error?

@rickgds80 how did you resolve this in the end ? 😌 

Best regards

**Comment by RyanJarv** [comment]
@YorkshireGold do you know what python version your using?

> python3 --version

Should print that
