### ISSUE TITLE
Terrform error

### ISSUE THREAD

**Issue by sidejackthenativity** [RhinoSecurityLabs/cloudgoat#75]
Hi there,

I am getting the following error:

Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.

Is there a Terraform config file I need to adjust?

Thanks!

**Comment by RyanJarv** [comment]
@sidejackthenativity Sorry for the delayed response here.

Typically there is, for cloudgoat however the AWS profile is configured in `config.yml`. It should look something like this:
```
- default-profile: default
```

Running `./cloudgoat.py config profile` will also set this up for you.

I would check what this is set to and run the following command to make sure your AWS credentials are set up correctly.
> aws --profile default sts get-caller-identity

Just replace default there with whatever is set in `config.yml`. If the awscli command doesn't work then you'll need to ensure your ~/.aws/config and ~/.aws/credentials files are set up with valid creds.

**Comment by RyanJarv** [comment]
I'm going close this issue since we haven't heard back in a while. If you're still having issues with this feel free to open a new issue and reference this one though.
