### ISSUE TITLE
first run of ./start.sh fails on credfile.write("Administrator Password:   " + clearpass + '\n')

### ISSUE THREAD

**Issue by kbroughton** [RhinoSecurityLabs/cloudgoat#9]
I'm running on osx 10.13.6
with brew installed gpg

$ gpg --version
gpg (GnuPG) 2.2.4
libgcrypt 1.8.2
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/kbroughton/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

Here is the error:

gpg: encrypted with 2048-bit RSA key, ID 2F5443323CA9803B, created 2018-08-01
      "CloudGoat"
Traceback (most recent call last):
  File "./extract_creds.py", line 14, in <module>
    credfile.write("Administrator Password:   " + clearpass + '\n')
TypeError: must be str, not bytes

**Comment by SpenGietz** [comment]
What version of python are you running? I suspect that may have something to do with it

**Comment by SpenGietz** [comment]
I fixed it to support Python3 and merged in here: https://github.com/RhinoSecurityLabs/cloudgoat/pull/11. Thanks for the report!

**Comment by kbroughton** [comment]
I can confirm that fixed it.  Thanks!
