### ISSUE TITLE
./cloudgoat destroy scenario -error

### ISSUE THREAD

**Issue by shooricg** [RhinoSecurityLabs/cloudgoat#92]
Hey guys,
When I run the terraform destroy command I get the following error.

This happens for all of the scenarios.  Do you know this can be?

Destroy "lambda_privesc"? [y/n]: y
╷
│ Error: Failed to parse command-line flags
│
│ flag provided but not defined: -force
╵

For more help on using this command, run:
  terraform destroy -help

[cloudgoat] Error while running `terraform destroy`.
    exit code: 1
    stdout: None
    stderr: None

Destruction complete.
    0 scenarios successfully destroyed
    2 destroys failed
    0 skipped

**Comment by RyanJarv** [comment]
I imagine this is related to the version of terraform that is running.

Do you mind sharing the output from `terraform version` and `git rev-parse HEAD` (should be ran from inside the CloudGoat repo)?

**Comment by shooricg** [comment]
Hey, thank you for getting back to me. This what I assumed. Originally I had Terraform v1.0,0., right after creating this issue, I downgraded to v0.15, and 'Destroy' begin work, even on the resources created with Terraform v1.0,0

**Comment by j0eblow** [comment]
Hi @shooricg this should be fixed now. Can you give it a try and report back? Thank you.

**Comment by shooricg** [comment]
@j0eblow Thank you all works now. Verified for v1.0.1.

**Comment by j0eblow** [comment]
Closing this now as the issue has been fixed.
