### ISSUE TITLE
Hi bro 

### ISSUE THREAD

**Issue by koreatlwls** [RhinoSecurityLabs/cloudgoat#98]
how to solve this error ?? 
I want to create cloud_breach_s3

Error: Error creating S3 bucket: InvalidBucketName: The specified bucket is not valid.
│       status code: 400, request id: [         ], host id: [                                         ]
│ 
│   with aws_s3_bucket.cg-cardholder-data-bucket,
│   on s3.tf line 2, in resource "aws_s3_bucket" "cg-cardholder-data-bucket":
│    2: resource "aws_s3_bucket" "cg-cardholder-data-bucket" {
│ 
╵

[cloudgoat] Error while running `terraform apply`.
    exit code: 1
    stdout: None
    stderr: None

**Comment by hackingprofessional** [comment]
I have the same problem! :(

**Comment by christophetd** [comment]
Fixed in #102

**Comment by RyanJarv** [comment]
Just merged @christophetd's fix for this. If you update to the latest commit and rerun ./cloudgoat.py create cloud_breach_s3 it should work now.

If you run into any issues go ahead and open a new issue.
